import { GitHubIcon } from '../icons'
import { ArrowRight, BookOpen, Database, ExternalLink, FileSearch, Link2, ShieldCheck, Sparkles, type LucideIcon } from 'lucide-react'

type TraceFeature = { icon: LucideIcon; title: string; description: string }
const traceFeatures: TraceFeature[] = [
  { icon: Database, title: 'Structured evidence', description: 'Categories stay separate so coverage is easy to inspect.' },
  { icon: FileSearch, title: 'Source audit', description: 'Review provider, author, license, date, and confidence.' },
  { icon: Link2, title: 'Stable links', description: 'Every accepted item points back to its public source.' },
  { icon: ShieldCheck, title: 'No invented facts', description: 'Missing evidence stays missing instead of becoming copy.' },
  { icon: Sparkles, title: 'Grounded assistant', description: 'Ask questions against the current profile and citations.' },
  { icon: ExternalLink, title: 'Open providers', description: 'Built around public datasets and transparent boundaries.' },
]

function TerminalWindow() {
  return <div className="relative"><div aria-hidden="true" className="absolute -inset-6 bg-gradient-to-br from-brand-blue/20 via-brand-purple/10 to-brand-cyan/20 blur-3xl opacity-60 pointer-events-none" /><div className="relative rounded-xl border border-white/10 bg-black/70 backdrop-blur-sm overflow-hidden crt-scanlines crt-beam"><div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-white/[0.03]"><span className="w-3 h-3 rounded-full bg-red-500/80" /><span className="w-3 h-3 rounded-full bg-yellow-500/80" /><span className="w-3 h-3 rounded-full bg-green-500/80" /><span className="ml-2 text-xs text-white/40 font-mono">trace — sources</span></div><div className="p-4 md:p-6 font-mono text-[13px] md:text-sm leading-relaxed"><div className="flex items-center gap-2"><span className="text-green-400">~</span><span className="text-green-400">$</span><span className="text-white">trace inspect "University of Toronto"</span></div><div className="mt-3 space-y-1 text-white/70"><div><span className="text-green-400">✓</span> Resolving university</div><div><span className="text-green-400">✓</span> Collecting public sources</div><div><span className="text-green-400">✓</span> Checking provenance</div><div><span className="text-green-400">✓</span> Marking evidence gaps</div></div><div className="mt-3 text-white/50">{'  → Profile:    '}<span className="text-white/80">ready with citations</span></div><div className="mt-3 flex items-center gap-2"><span className="text-green-400">~</span><span className="text-green-400">$</span><span className="inline-block w-2 h-4 bg-green-400 animate-pulse" aria-hidden="true" /></div></div></div></div>
}

export function OpenSource() {
  return <section className="px-6 md:px-12 lg:px-20"><div className="max-w-7xl mx-auto rounded-2xl nice-shadow overflow-hidden bg-neutral-950 text-white relative"><div className="relative px-6 md:px-12 lg:px-16 pt-16 md:pt-24 pb-12 md:pb-16"><div aria-hidden="true" className="absolute inset-0 opacity-[0.04] pointer-events-none [background-image:linear-gradient(to_right,white_1px,transparent_1px),linear-gradient(to_bottom,white_1px,transparent_1px)] [background-size:40px_40px]" /><div className="relative grid gap-10 lg:gap-16 lg:grid-cols-2 items-center"><div className="flex flex-col gap-4"><h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight leading-[1.1]">Прозрачный протокол проверки</h2><p className="text-lg md:text-xl font-medium text-white/80">Построен на источниках, а не на впечатлении.</p><p className="text-base text-white/60 max-w-md">TRACE показывает путь от открытого провайдера до профиля университета. Проверяйте материалы вручную, сохраняйте ссылки и видьте, где данных недостаточно.</p><div className="flex flex-wrap gap-3 pt-2"><a href="https://github.com/learnhouse/learnhouse" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white text-neutral-950 px-5 py-2.5 text-sm font-semibold hover:bg-white/90 transition-colors"><GitHubIcon size={18} />Исходный код</a><a href="/trace" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 text-white px-5 py-2.5 text-sm font-semibold hover:bg-white/10 transition-colors"><BookOpen size={18} />Открыть TRACE</a></div></div><TerminalWindow /></div></div><div className="h-px bg-white/10" /><div className="relative px-6 md:px-12 lg:px-16 py-16 md:py-24"><div className="flex flex-col items-start gap-4 mb-10 md:mb-14 max-w-2xl"><h3 className="text-2xl md:text-3xl lg:text-4xl font-bold tracking-tight">Что остаётся под контролем</h3><p className="text-lg md:text-xl font-medium text-white/80">Никаких скрытых подмен.</p><p className="text-base text-white/60">Каждый блок профиля можно проверить по источнику, категории и границам доступных данных.</p><a href="/trace#sources" className="inline-flex items-center gap-2 rounded-full bg-white text-neutral-950 px-5 py-2.5 text-sm font-semibold hover:bg-white/90 transition-colors mt-2">Посмотреть доказательства<ArrowRight size={16} /></a></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-px bg-white/10 rounded-xl overflow-hidden border border-white/10">{traceFeatures.map(({ icon: Icon, title, description }) => <div key={title} className="bg-neutral-950 p-6 md:p-8 flex flex-col gap-3 hover:bg-neutral-900/60 transition-colors"><div className="flex items-center justify-center w-10 h-10 rounded-lg bg-white/5 border border-white/10 text-white"><Icon size={20} /></div><h4 className="text-base font-semibold text-white">{title}</h4><p className="text-sm text-white/50 leading-relaxed">{description}</p></div>)}</div></div></div></section>
}
